/* ═══════════════════════════════════════════════════════════════════════
   Fashion Forever · Pretty Pixie — Performance Dashboard CONFIG
   Source: FashionForever_MarApr_Analysis_v6
     · Sheet 16 (Campaign → Ad Set → Ad execution spec)
     · Section J KPI Framework (16 KPIs)
     · Section 14 Margin Protection (10 rules)
     · Sheet 16 Section 3 (Kill & Refresh rules)
     · Action Plan Section 9 (Audience segments)
   ─────────────────────────────────────────────────────────────────────
   EDIT THIS FILE to update targets. App reads window.PIXIE_CONFIG.
   No need to touch index.html when targets change.
   ═══════════════════════════════════════════════════════════════════ */

window.PIXIE_CONFIG = {

  /* ── META ACCOUNT ─────────────────────────────────────────────── */
  meta: {
    accountId: '2295943007451315',
    apiVersion: 'v20.0',
    attribution: 'use_account_attribution_setting=true&default_summary=true',
  },

  /* ── BUSINESS DECISIONS (locked) ──────────────────────────────── */
  business: {
    grossMargin: 0.55,
    shippingPerOrder: 120,
    codHandlingFee: 99,
    corePair:    { name: 'Core Pair',    price: 7800,  mrp: 8998,  discountPct: 13.3, url: '/collections/core-pair' },
    trio:        { name: 'Premium Trio', price: 10950, mrp: 13497, discountPct: 18.9, url: '/collections/premium-trio' },
    prepaidIncentivePct: 10,
    freeShippingThreshold: 3500,
    legacyFlatOff: { amount: 1000, sunsetTarget: 'Phase 2' },
  },

  /* ── PHASES (90-day plan) ─────────────────────────────────────── */
  phaseStartIST: '2026-05-11T00:00:00+05:30',
  phases: [
    { n: 1, name: 'STABILIZE', days: 30, merTarget: [1.6, 1.9], merKill: 1.4, dailyBudget: 54000 },
    { n: 2, name: 'BUILD',     days: 30, merTarget: [2.2, 2.7], merKill: 1.5, dailyBudget: 62000 },
    { n: 3, name: 'SCALE',     days: 30, merTarget: [2.8, 3.5], merKill: 1.7, dailyBudget: 75000 },
  ],

  /* ── 9 CAMPAIGNS (from Sheet 16) ──────────────────────────────── */
  campaigns: [
    { slot: 'C1', type: 'prospecting', product: 'core_pair',
     id: '120244058093930714',
      name: 'BROAD · TIER1 CITIES · F25-54 · CORE PAIR',
      spendShare: 26,
      dailyBudget:  { p1: 14000, p2: 14000, p3: 15000 },
      predictedRoas:{ p1: [1.4, 1.6], p2: [1.5, 1.7], p3: [1.6, 1.9] },
      targetCpa: 3200, cpaCap: 3500, targetAov: 7800, freqCap: 2.5, killSpend: 15000, killRoas: 1.4,
      adSets: 3, adsP1: 8, adsP2: 8, adsP3: 8,
      audience: 'F 25-54 · Top 14 cities · EXCL M18-34, past 90d',
    },
    { slot: 'C2', type: 'prospecting', product: 'core_pair',
      name: 'BROAD · TIER2 CITIES · F25-54 · BUNDLE',
      spendShare: 11,
      dailyBudget:  { p1: 6000, p2: 6000, p3: 7000 },
      predictedRoas:{ p1: [1.6, 1.8], p2: [1.7, 2.0], p3: [1.8, 2.1] },
      targetCpa: 2800, cpaCap: 3500, targetAov: 7800, freqCap: 2.5, killSpend: 10000, killRoas: 1.5,
      adSets: 2, adsP1: 4, adsP2: 4, adsP3: 4,
      audience: 'F 25-54 · Tier-2 (Coimbatore, Vadodara, etc.) · EXCL Tier-1',
    },
    { slot: 'C3', type: 'prospecting', product: 'mixed',
      name: 'BROAD · REST OF INDIA · PREPAID ONLY',
      spendShare: 7,
      dailyBudget:  { p1: 4000, p2: 4000, p3: 5000 },
      predictedRoas:{ p1: [1.0, 1.3], p2: [1.2, 1.5], p3: [1.3, 1.6] },
      targetCpa: 2800, cpaCap: 3000, targetAov: 5500, freqCap: 2.5, killSpend: 10000, killRoas: 1.0,
      adSets: 1, adsP1: 3, adsP2: 3, adsP3: 3,
      audience: 'F 25-54 · All India minus Tier-1/2 + 5 high-cancel states',
    },
    { slot: 'C4', type: 'prospecting', product: 'mixed',
      name: 'BROAD · F25-34 · GROWTH CREATORS',
      spendShare: 7,
      dailyBudget:  { p1: 4000, p2: 5000, p3: 6000 },
      predictedRoas:{ p1: [1.4, 1.6], p2: [1.5, 1.7], p3: [1.5, 1.8] },
      targetCpa: 3100, cpaCap: 3500, targetAov: 5800, freqCap: 2.5, killSpend: 15000, killRoas: 1.3,
      adSets: 2, adsP1: 4, adsP2: 4, adsP3: 4,
      audience: 'F 25-34 · All India · younger creators (Akshata, Sonal)',
    },
    { slot: 'C5', type: 'prospecting', product: 'core_pair',
      name: 'LAL · TOP-LTV 1% · FRESH',
      spendShare: 7,
      dailyBudget:  { p1: 4000, p2: 5000, p3: 6000 },
      predictedRoas:{ p1: [1.3, 1.5], p2: [1.4, 1.6], p3: [1.5, 1.7] },
      targetCpa: 3400, cpaCap: 4000, targetAov: 6200, freqCap: 2.5, killSpend: 12000, killRoas: 1.3,
      adSets: 1, adsP1: 3, adsP2: 3, adsP3: 3,
      audience: 'Lookalike 1% Top-LTV-90d · refresh seed monthly',
    },
    { slot: 'C6', type: 'prospecting', product: 'trio',
      name: 'PREMIUM ANCHOR · F30-50 · CORE CITIES',
      spendShare: 6,
      dailyBudget:  { p1: 3000, p2: 4000, p3: 5000 },
      predictedRoas:{ p1: [1.2, 1.4], p2: [1.4, 1.7], p3: [1.5, 1.8] },
      targetCpa: 4200, cpaCap: 4500, targetAov: 8500, freqCap: 2.5, killSpend: 10000, killRoas: 1.1,
      adSets: 1, adsP1: 3, adsP2: 3, adsP3: 3,
      audience: 'F 30-50 · Top 14 cities · Premium SKUs',
    },
    { slot: 'C7', type: 'retargeting', product: 'dpa',
      name: 'RT · DPA · 7-DAY HOT',
      spendShare: 15,
      dailyBudget:  { p1: 8000, p2: 9000, p3: 10000 },
      predictedRoas:{ p1: [2.5, 3.0], p2: [3.0, 3.5], p3: [3.5, 4.5] },
      targetCpa: 1800, cpaCap: 2500, targetAov: 6800, freqCap: 3.5, killSpend: 5000, killRoas: 2.0,
      adSets: 1, adsP1: 4, adsP2: 4, adsP3: 4,
      audience: 'ATC + IC last 7d, NOT purchased',
    },
    { slot: 'C8', type: 'retargeting', product: 'mixed',
      name: 'RT · BRAND · 30-70 DAY WARM',
      spendShare: 13,
      dailyBudget:  { p1: 3000, p2: 6000, p3: 11000 },
      predictedRoas:{ p1: [1.7, 2.0], p2: [2.0, 2.5], p3: [2.3, 2.8] },
      targetCpa: 2600, cpaCap: 3000, targetAov: 6200, freqCap: 3.5, killSpend: 8000, killRoas: 1.5,
      adSets: 2, adsP1: 3, adsP2: 5, adsP3: 5,
      audience: 'VC + visitors 8-30d, then 31-70d (split in 2 ad sets)',
    },
    { slot: 'C9', type: 'reactivation', product: 'core_pair',
      name: 'REACTIVATION · PAST BUYER 60D+',
      spendShare: 12,
      dailyBudget:  { p1: 3000, p2: 7000, p3: 9000 },
      predictedRoas:{ p1: [3.5, 4.5], p2: [4.0, 5.0], p3: [4.5, 5.5] },
      targetCpa: 1500, cpaCap: 2000, targetAov: 6000, freqCap: 3.5, killSpend: 5000, killRoas: 2.5,
      adSets: 1, adsP1: 5, adsP2: 5, adsP3: 5,
      audience: 'Past purchasers 60+ days (Shopify CA)',
    },
  ],

  /* ── KPI FRAMEWORK · Section J (16 KPIs) ───────────────────────── */
  kpis: {
    /* GOLD ROW · the 6 that decide the future */
    mer: {
      label: 'MER · Blended ROAS', group: 'gold', fmt: 'x', inverse: false,
      baseline: 1.21, bands: { p1: [1.6, 1.9], p2: [2.2, 2.7], p3: [2.8, 3.5] },
      source: 'Meta', frequency: 'daily',
      mgmt: 'For every ₹1 spent on ads, how much revenue we make',
      breachAction: 'Pause new tests; review prospecting ad sets',
    },
    ncRoas: {
      label: 'New-Customer ROAS', group: 'gold', fmt: 'x', inverse: false,
      baseline: 1.0, bands: { p1: [1.2, 1.4], p2: [1.3, 1.5], p3: [1.4, 1.6] },
      source: 'Shopify cohort + Meta', frequency: 'weekly',
      mgmt: 'Revenue from FIRST-time customers per ₹1 of prospecting spend',
      breachAction: 'Reduce prospecting cap; refresh creative',
    },
    aov: {
      label: 'Net AOV', group: 'gold', fmt: '₹', inverse: false,
      baseline: 4505, bands: { p1: [5200, 5500], p2: [5800, 6200], p3: [6200, 6800] },
      source: 'Shopify', frequency: 'daily',
      mgmt: 'Average order value · Core Pair anchor ₹7,800',
      breachAction: 'Audit which segment is dragging AOV',
    },
    contribMargin: {
      label: 'Contribution Margin', group: 'gold', fmt: 'L', inverse: false,
      baseline: -1300000, bands: { p1: [-200000, 300000], p2: [400000, 800000], p3: [900000, 1500000] },
      source: 'Calculation', frequency: 'weekly',
      mgmt: 'Revenue × 55% GM minus Ad Spend minus ₹120/order shipping',
      breachAction: 'Halt new tests; review highest-spend bleeders',
    },
    cac: {
      label: 'CAC · Customer Acquisition Cost', group: 'gold', fmt: '₹', inverse: true,
      baseline: 3500, bands: { p1: [3000, 3400], p2: [2800, 3200], p3: [2600, 3000] },
      source: 'Shopify cohort + Meta', frequency: 'weekly',
      mgmt: 'Prospecting spend / new customers (LOWER is better)',
      breachAction: 'Refresh creative; cut high-CPM ad sets',
    },
    repeatRate: {
      label: 'Repeat Rate (60d)', group: 'gold', fmt: '%', inverse: false,
      baseline: null, bands: { p1: null, p2: [8, 12], p3: [12, 18] },
      source: 'Shopify cohort', frequency: 'weekly',
      mgmt: 'Customers who buy again within 60 days · path to 5x MER',
      breachAction: 'PixieCredits expansion; email flow audit',
    },
    /* SILVER ROW · tactical */
    cacPayback: {
      label: 'CAC Payback (months)', group: 'silver', fmt: 'mo', inverse: true,
      baseline: 12, bands: { p1: [8, 10], p2: [6, 8], p3: [4, 6] },
      source: 'Calculation', frequency: 'monthly',
      mgmt: 'Months to recover CAC via repeat purchases',
      breachAction: 'Reduce prospecting; redirect to retention',
    },
    prepaidMix: {
      label: 'Prepaid Mix %', group: 'silver', fmt: '%', inverse: false,
      baseline: 35.4, bands: { p1: [45, 50], p2: [52, 58], p3: [55, 60] },
      source: 'Shopify', frequency: 'daily',
      mgmt: '% of orders paid upfront (UPI/Card) vs COD',
      breachAction: 'Audit PIXIE10 visibility in cart/checkout',
    },
    cancelRate: {
      label: 'Cancel Rate %', group: 'silver', fmt: '%', inverse: true,
      baseline: 10.5, bands: { p1: [8, 10], p2: [6, 8], p3: [5, 7] },
      source: 'Shopify', frequency: 'daily',
      mgmt: '% of orders cancelled before delivery',
      breachAction: 'COD calling SOP; high-cancel state review',
    },
    discountPct: {
      label: 'Discount % of Subtotal', group: 'silver', fmt: '%', inverse: true,
      baseline: 29.8, bands: { p1: [12, 15], p2: [8, 10], p3: [5, 8] },
      source: 'Shopify', frequency: 'daily',
      mgmt: 'Total discount given / subtotal — margin killer above 12%',
      breachAction: 'Halt any campaign exceeding 12%',
    },
    clickToSession: {
      label: 'Click → Session %', group: 'silver', fmt: '%', inverse: false,
      baseline: 24, bands: { p1: [40, 100], p2: [50, 100], p3: [60, 100] },
      source: 'Meta + GA4', frequency: 'weekly',
      mgmt: '% of paid clicks that actually load the site (76% leaking today)',
      breachAction: 'Mobile speed audit; in-app browser test',
    },
    bundleAttach: {
      label: 'Bundle Attach Rate', group: 'silver', fmt: '%', inverse: false,
      baseline: 0, bands: { p1: [8, 12], p2: [15, 25], p3: [25, 35] },
      source: 'Shopify', frequency: 'daily',
      mgmt: '% of orders that include Core Pair or Trio bundle',
      breachAction: 'Bundle creative refresh; PDP merchandising',
    },
    emailRev: {
      label: 'Klaviyo Email Rev/wk', group: 'silver', fmt: 'L', inverse: false,
      baseline: 0, bands: { p1: [40000, 60000], p2: [70000, 100000], p3: [100000, 150000] },
      source: 'Klaviyo', frequency: 'weekly',
      mgmt: 'Owned-channel revenue · capped only by list size',
      breachAction: 'List growth + flow optimization',
    },
    whatsappRev: {
      label: 'WhatsApp Rev/wk', group: 'silver', fmt: 'L', inverse: false,
      baseline: 0, bands: { p1: [20000, 40000], p2: [40000, 70000], p3: [60000, 100000] },
      source: 'BiteSpeed', frequency: 'weekly',
      mgmt: 'BiteSpeed-attributed revenue',
      breachAction: 'Broadcast cadence + ATC flow audit',
    },
    refundRate: {
      label: 'Refund Rate %', group: 'silver', fmt: '%', inverse: true,
      baseline: 12.3, bands: { p1: [0, 8], p2: [0, 6], p3: [0, 5] },
      source: 'Shopify', frequency: 'weekly',
      mgmt: 'Refunds / net revenue — brand damage + repeat killer',
      breachAction: 'Top 3 SKU audit; pause ads on refund-driving SKUs',
    },
    frequency: {
      label: 'Top Ad Set Frequency', group: 'silver', fmt: 'x', inverse: true,
      baseline: null, bands: { p1: [0, 2.5], p2: [0, 2.5], p3: [0, 2.5] },
      source: 'Meta', frequency: 'daily',
      mgmt: 'Avg impressions per person · creative fatigue above 2.5x',
      breachAction: 'Refresh creative or expand audience',
    },
    /* ─ CONVERSION FUNNEL KPIs (Section 4 / CRO leaks) ─ */
    ctr: {
      label: 'CTR · All Clicks', group: 'silver', fmt: '%', inverse: false,
      baseline: null, bands: { p1: [1.0, 100], p2: [1.2, 100], p3: [1.5, 100] },
      source: 'Meta', frequency: 'daily',
      mgmt: '% of impressions clicked · benchmark ≥1.5%',
      breachAction: 'Hook variant test · first-3-sec audit',
    },
    linkCtr: {
      label: 'Link CTR', group: 'silver', fmt: '%', inverse: false,
      baseline: null, bands: { p1: [1.0, 100], p2: [1.2, 100], p3: [1.5, 100] },
      source: 'Meta', frequency: 'daily',
      mgmt: '% reaching the link · benchmark ≥1.0% cold, ≥1.5% warm',
      breachAction: 'CTA fix · LP relevance check',
    },
    cvr: {
      label: 'CVR · Click → Purchase', group: 'silver', fmt: '%', inverse: false,
      baseline: null, bands: { p1: [1.5, 100], p2: [2.0, 100], p3: [2.5, 100] },
      source: 'Meta', frequency: 'daily',
      mgmt: '% of link-clickers who buy · the conversion engine',
      breachAction: 'Funnel audit — find the drop-off stage',
    },
    atcRate: {
      label: 'ATC Rate (per click)', group: 'silver', fmt: '%', inverse: false,
      baseline: null, bands: { p1: [4.0, 100], p2: [5.0, 100], p3: [6.0, 100] },
      source: 'Meta', frequency: 'daily',
      mgmt: '% adding to cart from link click · benchmark ≥5%',
      breachAction: 'PDP merch · price visibility · trust badges',
    },
    icToPurchaseKpi: {
      label: 'IC → Purchase %', group: 'silver', fmt: '%', inverse: false,
      baseline: 36, bands: { p1: [40, 100], p2: [45, 100], p3: [50, 100] },
      source: 'Meta + Shopify', frequency: 'daily',
      mgmt: 'Razorpay/GoKwik checkout health · was 48.8% baseline · 36% today',
      breachAction: 'OTP delivery audit · payment method ordering',
    },
    hookRate: {
      label: 'Hook Rate (3-sec)', group: 'silver', fmt: '%', inverse: false,
      baseline: null, bands: { p1: [25, 100], p2: [28, 100], p3: [30, 100] },
      source: 'Meta', frequency: 'daily',
      mgmt: '% who watch first 3 seconds · creative quality signal',
      breachAction: 'Hook variant brief · first 3-sec must show product on body',
    },
    cpc: {
      label: 'CPC · Link Click', group: 'silver', fmt: '₹', inverse: true,
      baseline: null, bands: { p1: [0, 40], p2: [0, 35], p3: [0, 30] },
      source: 'Meta', frequency: 'daily',
      mgmt: 'Cost per link click · lower is better · benchmark ≤₹30',
      breachAction: 'Audience/placement audit · creative refresh',
    },
  },

  /* ── MARGIN PROTECTION RULES · Section 14 (10 rules) ──────────── */
  marginRules: [
    { id: 'R1', name: 'Discount cap',         severity: 'high',
      trigger: 'Discount % of subtotal exceeds 12%',
      action: 'Halt the offer immediately',
      why: 'At 50% GM, every 1% of discount = 2% of contribution profit. >12% wipes margin.',
      kpi: 'discountPct', op: '>', threshold: 12, source: 'shopify' },
    { id: 'R2', name: 'ROAS floor',           severity: 'high',
      trigger: 'Any ad set <1.4x ROAS for 7 days at ₹15K+ spend',
      action: 'Auto-pause the ad set',
      why: 'Below 1.4x ROAS at 50% GM = losing money on every ad-driven order.',
      checkType: 'adset_roas_floor', threshold: 1.4, spendGate: 15000 },
    { id: 'R3', name: 'Prospecting cap',      severity: 'medium',
      trigger: 'Prospecting % of spend exceeds phase target by 5pp',
      action: 'Throttle prospecting -15%',
      why: 'Prevents over-acquisition during retention build phase.',
      checkType: 'stage_mix', overBy: 5 },
    { id: 'R4', name: 'AOV floor',            severity: 'medium',
      trigger: 'Daily AOV < ₹4,800 for 3 days',
      action: 'Investigate which segment is dragging; pause lowest-AOV campaign',
      why: 'Confirms pricing changes are sticking.',
      kpi: 'aov', op: '<', threshold: 4800 },
    { id: 'R5', name: 'COD % cap',            severity: 'medium',
      trigger: 'COD orders exceed 50% of new orders',
      action: 'Tighten COD restrictions; expand prepaid-only states',
      why: 'COD cancels are pure-loss revenue events.',
      kpi: 'codPct', op: '>', threshold: 50, source: 'shopify' },
    { id: 'R6', name: 'Refund rate',          severity: 'medium',
      trigger: 'Refunds exceed 5% of net revenue weekly',
      action: 'Top 3 SKU audit; halt ads on refund-driving SKUs',
      why: 'Refunds = brand damage + repeat killer.',
      kpi: 'refundRate', op: '>', threshold: 5, source: 'shopify' },
    { id: 'R7', name: 'CAC payback',          severity: 'high',
      trigger: 'CAC payback exceeds 8 months',
      action: 'Reduce prospecting; redirect to retention',
      why: 'Can\'t fund next acquisition cycle if CAC takes >8mo to recover.',
      kpi: 'cacPayback', op: '>', threshold: 8 },
    { id: 'R8', name: 'Repeat rate (D60+)',   severity: 'high',
      trigger: '60-day repeat rate <12% after Day 60',
      action: 'PixieCredits expansion; email flow audit',
      why: 'Repeat rate IS the path to 5x. Without it, forever in negative-contrib prospecting.',
      kpi: 'repeatRate', op: '<', threshold: 12, phaseGate: 2 },
    { id: 'R9', name: 'NC-ROAS masking',      severity: 'high',
      trigger: 'NC-ROAS < 1.3x while total ROAS > 1.7x',
      action: 'Retention is hiding prospecting failure — investigate',
      why: 'Prevents the "we\'re scaling" delusion when real new acquisition is degrading.',
      checkType: 'nc_roas_mask' },
    { id: 'R10', name: 'Bundle inventory',    severity: 'medium',
      trigger: 'Bundle SKU <14 days of inventory cover',
      action: 'Halt bundle ads; merchandise alternative SKUs',
      why: 'Prevents stockouts that kill momentum.',
      checkType: 'inventory', source: 'shopify' },
  ],

  /* ── KILL & REFRESH RULES · Sheet 16 Section 3 ─────────────────── */
  killRules: {
    coldProspecting: [
      { atSpend: 15000, roas: 1.0, op: '<',  level: 'kill',    action: 'KILL within 24hr',                                auto: true,  why: 'Direct contribution-negative' },
      { atSpend: 15000, roas: 1.4, op: '<',  level: 'refresh', action: 'REFRESH hook (Higgsfield variant) · give 7d',    auto: false, why: 'Hook may be the issue not body' },
      { atSpend: 15000, roas: 1.5, op: '>=', level: 'scale',   action: 'PROMOTE — budget +20%; brief 2 derivatives',     auto: true,  why: 'Winner identified — extract pattern' },
    ],
    warmRetargeting: [
      { atSpend: 8000,  roas: 1.5, op: '<',  level: 'kill',    action: 'KILL within 48hr',                               auto: true,  why: 'Warm should easily exceed 1.5x' },
      { atSpend: 8000,  roas: 2.5, op: '>=', level: 'scale',   action: 'PROMOTE; brief derivatives',                     auto: false, why: 'Strong performer' },
    ],
    hotRetargetingDPA: [
      { atSpend: 5000,  roas: 2.0, op: '<',  level: 'audit',   action: 'CATALOG FEED AUDIT (not creative)',              auto: false, why: 'DPA failures usually feed issues' },
    ],
    reactivation: [
      { atSpend: 5000,  roas: 2.5, op: '<',  level: 'refresh', action: 'REFRESH hook + expand audience window',         auto: false, why: 'Past buyers should hit 4x+' },
    ],
    universal: [
      { metric: 'frequency', op: '>', threshold: 3.0, level: 'refresh', action: 'REFRESH creative immediately',           auto: false, why: 'Fatigue active (with ROAS dropping)' },
      { metric: 'frequency', op: '>', threshold: 3.5, level: 'pause',   action: 'PAUSE until refresh ready',              auto: true,  why: 'Better to go dark than burn audience' },
      { adsetRoas7d: 0.8,    op: '<', level: 'pause',                   action: 'AUTO-PAUSE ad set',                      auto: true,  why: 'Audience or angle broken' },
    ],
  },

  /* ── AUDIENCE SEGMENTS · Action Plan Section 9 ─────────────────── */
  segments: [
    { key: 'F.35-44', label: 'Female 35-44', tag: 'CORE — gold standard', revShare: 40.2, baselineRoas: 1.55, targetRoas: [1.7, 2.0], targetSpendShare: [35, 40], action: 'Lock budget here. Top 5 creators. Bundle creatives.', confidence: 'High', priority: 1 },
    { key: 'F.25-34', label: 'Female 25-34', tag: 'GROWTH', revShare: 21.0, baselineRoas: 1.39, targetRoas: [1.5, 1.7], targetSpendShare: [20, 25], action: 'Develop deliberately — younger creators (Akshata, Sonal, Astha).', confidence: 'Directional', priority: 2 },
    { key: 'F.45-54', label: 'Female 45-54', tag: 'STEADY', revShare: 14.2, baselineRoas: 1.23, targetRoas: [1.3, 1.5], targetSpendShare: [12, 15], action: 'Maintain. Premium SKU push works here.', confidence: 'High', priority: 3 },
    { key: 'M.35-44', label: 'Male 35-44',   tag: 'SURPRISE', revShare: 10.0, baselineRoas: 1.54, targetRoas: [1.5, 1.8], targetSpendShare: [5, 8], action: 'Under-targeted. Test ₹3K/day husband-as-buyer angle.', confidence: 'Directional', priority: 4 },
    { key: 'F.18-24', label: 'Female 18-24', tag: 'VOLATILE', revShare: 2.0,  baselineRoas: 1.13, targetRoas: null, targetSpendShare: [0, 0], action: 'Skip conversion campaigns. Awareness only.', confidence: 'High', priority: 5 },
    { key: 'F.55-64', label: 'Female 55-64', tag: 'MAYBE',    revShare: 2.4,  baselineRoas: 0.93, targetRoas: [1.0, 1.2], targetSpendShare: [0, 2], action: 'Single ad set test in C6 only.', confidence: 'Directional', priority: 6 },
    { key: 'M.18-24', label: 'Male 18-24',   tag: 'KILL · permanent exclusion', revShare: 2.5, baselineRoas: 0.32, targetRoas: null, targetSpendShare: [0, 0], action: 'EXCLUDED. If spend > ₹0 here, exclusion is broken.', confidence: 'High', priority: 7, kill: true },
    { key: 'M.25-34', label: 'Male 25-34',   tag: 'KILL · permanent exclusion', revShare: 2.5, baselineRoas: 0.62, targetRoas: null, targetSpendShare: [0, 0], action: 'EXCLUDED. If spend > ₹0 here, exclusion is broken.', confidence: 'High', priority: 8, kill: true },
  ],

  /* ── FUNNEL STAGE ALLOCATION (60/28/12 locked) ────────────────── */
  stageAllocation: {
    p1: { prospecting: 75, retargeting: 20, reactivation: 5 },
    p2: { prospecting: 65, retargeting: 25, reactivation: 10 },
    p3: { prospecting: 60, retargeting: 28, reactivation: 12 },
  },

  /* ── ASSET COUNT TARGETS per phase ───────────────────────────── */
  assetTargets: {
    p1: { activeCampaigns: 9, activeAdSets: 20, activeAds: 44, avgSpendPerAdSet: 2700 },
    p2: { activeCampaigns: 9, activeAdSets: 23, activeAds: 55, avgSpendPerAdSet: 2700 },
    p3: { activeCampaigns: 9, activeAdSets: 25, activeAds: 62, avgSpendPerAdSet: 2950 },
  },

  /* ── 22-ITEM PRE-FLIGHT CHECKLIST · Sheet 16 Section 4 ────────── */
  preflightChecklist: [
    { n: 1,  item: '4 hero creators shot (Aveera, Astha, Nikita, Sonal) — 16+ reels', verifier: 'Marketing Lead', category: 'Creative' },
    { n: 2,  item: 'Akshata + Meera shoots complete — 2+4 assets',                    verifier: 'Marketing Lead', category: 'Creative' },
    { n: 3,  item: 'Astha prepaid-concept reel done',                                  verifier: 'Production',     category: 'Creative' },
    { n: 4,  item: '15 Higgsfield AI ad variants generated',                           verifier: 'Marketing',      category: 'Creative' },
    { n: 5,  item: '30 best-seller SKU photos refreshed at 1080×1080',                 verifier: 'Photography',    category: 'Creative' },
    { n: 6,  item: 'Shopify Catalog feed synced to Meta · no rejected SKUs',           verifier: 'Tech',           category: 'Tech' },
    { n: 7,  item: 'Custom audiences built (Top-LTV-1pct, Past-60d, ATC-7d, VC-30d)',  verifier: 'Media buyer',    category: 'Audience' },
    { n: 8,  item: 'Lookalike 1% from Top-LTV-90d seed created',                       verifier: 'Media buyer',    category: 'Audience' },
    { n: 9,  item: 'Bundle PDPs live (Core Pair, Premium Trio)',                       verifier: 'Tech',           category: 'Web' },
    { n: 10, item: 'PIXIE10 prepaid-only code activated · tested on all rails',        verifier: 'Tech',           category: 'Offer' },
    { n: 11, item: 'COD disabled in 5 high-cancel states (RJ, BR, CG, GA, PB)',        verifier: 'Tech',           category: 'Checkout' },
    { n: 12, item: 'Free shipping >₹3,500 threshold live · ₹99 below',                 verifier: 'Tech',           category: 'Checkout' },
    { n: 13, item: 'Klaviyo flows live (welcome, post-purchase, abandoned)',           verifier: 'Marketing',      category: 'Retention' },
    { n: 14, item: 'BiteSpeed WhatsApp flows live (ATC 1hr/24hr/72hr)',                verifier: 'Marketing',      category: 'Retention' },
    { n: 15, item: 'M18-34 + 18 wasted cities excluded at account level',              verifier: 'Media buyer',    category: 'Audience' },
    { n: 16, item: 'ASP +10% live on all SKUs',                                        verifier: 'Founder',        category: 'Pricing' },
    { n: 17, item: 'Last-discount-month email blast sent',                             verifier: 'Marketing',      category: 'Comms' },
    { n: 18, item: 'Daily KPI dashboard built and accessible',                         verifier: 'Founder',        category: 'Reporting' },
    { n: 19, item: 'All 9 campaigns + 20 ad sets + 44 ads loaded in Meta',             verifier: 'Media buyer',    category: 'Setup' },
    { n: 20, item: 'Frequency caps + CPA caps set on all ad sets',                     verifier: 'Media buyer',    category: 'Setup' },
    { n: 21, item: 'Budget pacing set to standard (not accelerated)',                  verifier: 'Media buyer',    category: 'Setup' },
    { n: 22, item: 'Naming convention enforced (PS_/AS_/AD_)',                         verifier: 'Media buyer',    category: 'Setup' },
  ],

  /* ── DATE PRESETS for the picker ──────────────────────────────── */
  datePresets: [
    { label: 'Today',     v: 'today' },
    { label: 'Yesterday', v: 'yesterday' },
    { label: '3d',        v: 'last_3d' },
    { label: '7d',        v: 'last_7d' },
    { label: '14d',       v: 'last_14d' },
    { label: '28d',       v: 'last_28d' },
    { label: '30d',       v: 'last_30d' },
    { label: '60d',       v: 'last_60d' },
    { label: 'Month',     v: 'this_month' },
    { label: 'Last Mo.',  v: 'last_month' },
    { label: 'Max',       v: 'maximum' },
  ],
};
